"""Print how many shelf cameras each camera-tier face needs and write configs/cameras.yaml.

python scripts/plan_cameras.py [--layout configs/store_layout.yaml] [--out configs/cameras.yaml]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # run as a script from any folder

import yaml  # noqa: E402

from shelfpulse.layout import store_map  # noqa: E402
from shelfpulse.layout.camera_planner import (  # noqa: E402
    FacePlan,
    load_settings,
    plan,
    total_cameras,
)


def format_table(plans: list[FacePlan]) -> str:
    lines = [f"{'run':<4} {'face':<4} {'aisle':<6} {'W m':>5} {'N':>3}  positions (m from front)"]
    for p in plans:
        pos = ", ".join(f"{c.position_m:g}" for c in p.cameras)
        lines.append(
            f"{p.run:<4} {p.face:<4} {p.aisle_m:<6g} {p.width_m:>5.2f} {len(p.cameras):>3}  {pos}"
        )
        if p.unseen_bays:
            lines.append(f"     warning: no single camera sees {', '.join(p.unseen_bays)} whole")
    lines.append(f"TOTAL {total_cameras(plans)} cameras")
    return "\n".join(lines)


def to_yaml(plans: list[FacePlan]) -> str:
    cams = [
        {
            "id": c.id,
            "run": c.run,
            "face": c.face,
            "aisle": c.aisle_id,
            "position_m": c.position_m,
            "mount": c.mount,
            "xy_m": list(c.xy_m),
            "bays": list(c.bays),
        }
        for p in plans
        for c in p.cameras
    ]
    header = "# Generated by scripts/plan_cameras.py from configs/store_layout.yaml. Don't edit.\n"
    return header + yaml.safe_dump({"cameras": cams}, sort_keys=False, default_flow_style=None)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--layout", default="configs/store_layout.yaml")
    ap.add_argument("--out", type=Path, default=Path("configs/cameras.yaml"))
    ap.add_argument("--runs", help="comma-separated run ids (default: camera-tier runs)")
    ap.add_argument("--no-write", action="store_true", help="print only")
    args = ap.parse_args(argv)

    smap = store_map.load(args.layout)
    plans = plan(smap, args.runs.split(",") if args.runs else None, load_settings())
    print(format_table(plans))
    if not args.no_write:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(to_yaml(plans), encoding="utf-8")
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
